name: Node.js setup
description: Setup Node.js

inputs:
  node-version:
    description: "Node.js version"
    type: string
    required: true
    default: "22.x"

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false

    - name: Setup pnpm config
      shell: bash
      run: pnpm config set store-dir "$PNPM_CACHE_FOLDER"

    # # Makes sure the pnpm store path exists (which is exactly what setup-node cares about)
    #   - name: Verify PNPM Cache Directory
    #     run: |
    #       PNPM_STORE_PATH="$( pnpm store path --silent )"
    #       if [ ! -d "$PNPM_STORE_PATH" ]; then
    #         echo "PNPM store directory does not exist, creating it."
    #         mkdir -p "$PNPM_STORE_PATH"
    #       else
    #         echo "PNPM store directory exists."
    #       fi
    #   - name: Setup package manager cache
    #     uses: actions/setup-node@v4
    #     with:
    #       cache: 'pnpm'

    # - name: Setup Node.js v.${{ inputs.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ inputs.node-version }}
    #     cache: "pnpm"
    #     run_install: false

    #   - name: Setup pnpm config
    #     run: pnpm config set store-dir "$PNPM_CACHE_FOLDER"
