name: Node.js setup
description: Setup Node.js

inputs:
  node-version:
    description: "Node.js version"
    type: string
    required: true
    default: "22.x"

runs:
  using: composite
  steps:
    - name: Setup Node.js v.${{ inputs.node-version }}
      shell: bash
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
