packages:
  - "backend/*"
  - "frontend/*"
  - "packages/*"

catalog:
  "@biomejs/biome": 1.9.4
  "@hono/node-server": ^1.13.8
  "@hono/zod-openapi": ^0.19.2
  "@radix-ui/react-slot": ^1.1.2
  "@react-router/dev": ^7.2.0
  "@react-router/node": ^7.2.0
  "@react-router/serve": ^7.2.0
  "@storybook/react": ^8.6.7
  "@tailwindcss/vite": ^4.0.0
  "@types/node": ^20.11.17
  "@types/pg": ^8.11.11
  "@types/react": ^19.0.1
  "@types/react-dom": ^19.0.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^16.4.7
  drizzle-kit: ^0.30.6
  drizzle-orm: ^0.41.0
  hono: ^4.7.2
  isbot: ^5.1.17
  lucide-react: ^0.483.0
  pg: ^8.14.1
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router: ^7.2.0
  react-router-devtools: ^1.1.0
  tailwind-merge: ^3.0.2
  tailwindcss: ^4.0.0
  tsx: ^4.7.1
  tw-animate-css: ^1.2.4
  typescript: ^5.8.2
  vite: ^5.4.11
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.9
  zod: ^3.24.2
