name: Node.js setup

on:
  workflow_call:
    inputs:
      matrix:
        description: "Matrix of Node.js versions"
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(inputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Turbo
        run: npm install -g turbo@2.4.2

      - name: Run build
        run: turbo build
