name: Node.js setup

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        type: string
        required: true
        default: "22.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Turbo
        run: npm install -g turbo@2.4.2
