name: Node.js setup

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        type: string
        required: true
        default: "22.x"

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v.${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"
